### PR TITLE
fix(security): only allow LB egress to task on configured port

### PR DESCRIPTION
**Pull request by rtasson**
Jira: nada, 10%

#### Changes made
You asked for this for a bit Trey. This PR removes the default "allow all egress" rule on the load balancer security group and replaces it instead with explicit security group rules permitting access to every port defined in `var.container_ports`. This protects us against AWS's load balancer implementation getting hacked and an attacker having free egress on the internal network (though with these modules everything should have restrictive ingress rules.)

The way this behaves is a little odd; AWS creates this default "allow all egress" rule by default on every newly created security group, but Terraform removes it (see "NOTE on Egress rules" on [this page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group).) Seemingly as a result, this removal here doesn't register ([though it should](https://github.com/hashicorp/terraform-provider-aws/blob/44ca5e035f868abdd830b80557bc6233a20fed07/aws/resource_aws_security_group.go#L735)) and this will only apply to newly created resources unless we taint the existing ones. I'm fine to simply let this slightly more secure implementation percolate through Mixmax by attrition, given the low impact of this fix (it's more hygiene than anything else.)

#### Potential Risks
The load balancer could fail to talk to services.

#### Test Plan
I ~need~ would have liked to test this in Sandbox. I can't quite yet though because Sandbox has no certificate to use for HTTPS yet. I'm marking this as a draft until then.

#### Release Plan
:shipit:

#### Checklist
- [ ] Should this involve a live code review and/or demo?

### CODE REVIEW

**Comment by rtasson** [comment]
what do you make of this PR, @ttacon ?

**Review by ttacon — APPROVED** [review]
Honestly, I think that this is great. I agree, I'd love to see this tested on a service, trying to think of a good one...

**Comment by rtasson** [comment]
I might get around to testing this this upcoming week.

**Comment by bradvogel** [comment]
@shils should this be merged or closed?

**Comment by bradvogel** [comment]
Closing due to age.

**Pull request closed without merging**
